FROM ruby:2.5.1-alpine3.7

ENV LANG ja_JP.UTF-8

RUN apk --update add --no-cache \
      build-base linux-headers libxml2-dev libxslt-dev \
      postgresql-dev sudo tzdata vim \
      nodejs yarn

RUN cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
  && echo "Asia/Tokyo" > /etc/timezone
RUN adduser -D rails \
  && echo "rails ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER rails
WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock /usr/src/app/
RUN bundle install --jobs=4

CMD ["rails", "-v"]
