FROM ruby:2.5.1-alpine3.7

ENV LANG ja_JP.UTF-8

RUN apk --update add --no-cache \
      build-base libxml2-dev libxslt-dev linux-headers \
      bash postgresql-dev tzdata \
      nodejs yarn
RUN cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
  && echo "Asia/Tokyo" > /etc/timezone

WORKDIR /usr/src/app
RUN adduser -D rails \
  && chown -R rails /usr/src/app /usr/local/bundle

USER rails

COPY --chown=rails . /usr/src/app
RUN bundle install --jobs=4
RUN yarn install && rails webpacker:compile

CMD RAILS_ENV=development puma -C config/puma.rb
