version: 2

jobs:
  deploy:
    working_directory: /tmp/heroku_yml_test
    docker:
      - image: rvillage/heroku-cli:6.16-alpine
    steps:
      - checkout
      - run: apk --update add --no-cache git openssh
      - run:
          name: Deploy Heroku
          command: |
            heroku git:remote -a ${HEROKU_APP_NAME}2
            git push -f https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}2.git HEAD:refs/heads/master
            sleep 5
            heroku restart -a ${HEROKU_APP_NAME}2

workflows:
  version: 2

  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: nondocker
