version: 2

jobs:
  deploy:
    working_directory: /tmp/heroku_yml_test
    docker:
      - image: rvillage/heroku-cli:6.16-alpine
    steps:
      - checkout
      - run:
          name: Deploy Heroku
          command: git push -f https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git HEAD:refs/heads/master

workflows:
  version: 2

  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
